services:
  - type: web
    name: scadaconnectivity-app
    env: node
    region: oregon
    buildCommand: npm run build
    startCommand: node server.js
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 18
